manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # nice_oled
    - name: mctechnology17
      url-base: https://github.com/mctechnology17
    # pim447 trackball driver
    - name: t0bybr
      url-base: https://github.com/t0bybr
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    # nice_oled
    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main
    # pim447 trackball driver (PIM447 native pointing)
    - name: pim447
      remote: t0bybr
      revision: main
  self:
    path: config
